# Generated by Django 5.0.4 on 2024-04-15 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="youtubevideos",
            old_name="chanel",
            new_name="channel",
        ),
    ]
